name: 'Setup'

runs:
  using: "composite"
  steps:
    - name: Set up Python 3.6.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.9
      shell: bash
    - name: Update pip
      run: python -m pip install --upgrade pip
      shell: bash
    - name: Install python dependencies
      run: pip install -r requirements.txt
      shell: bash
