name: Lint Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: 'Lint Python'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.9
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install python dependencies
      run: pip install -r requirements.txt
    - name: Lint
      run: make lint
  test:
    name: 'Test Python'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.9
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install python dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: make test
